<?php
//$conn = mysqli_connect('localhost', 'u892177228_usr_IBE5aRna', 'Fl3$/zjsm', 'u892177228_db_IBE5aRna') or die('Connection Failed');
$conn = mysqli_connect('localhost', 'root', '', 'home_service_pro') or die('Connection Failed');
mysqli_set_charset($conn, "utf8mb4");
date_default_timezone_set('Asia/Manila');

// IMPORTANT: PHP's date_default_timezone_set() does NOT affect timestamps
// generated by MySQL (CURRENT_TIMESTAMP / NOW() / DEFAULT current_timestamp()).
// Those use the MySQL server's timezone (usually the hosting server's country).
// Force the session to Manila (+08:00) so ALL MySQL timestamps are local time,
// regardless of where the database is hosted. This must run on every connection.
if (!$conn->query("SET time_zone = '+08:00'")) {
    // Fallback: MySQL may reject the offset form on very old servers.
    $conn->query("SET time_zone = 'Asia/Manila'");
}